blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    path('quicknotes/', views.posts_list, name='post_list'),
    path('like/', views.like, name='like'),
    path('quicknotes/comments/', views.comments, name='comments'),
    path('quicknotes/<int:id>/<str:message>/', views.note, name='note'),
    path('quicknotes/<int:id>/', views.note, name='note'),
]

korean_notes/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
import datetime
from django.utils import timezone

class Note(models.Model):
    title = models.CharField(max_length=100)
    quick_note = models.TextField()
    pub_date = models.DateTimeField('date published')
    author = models.CharField(max_length=100)
    like = models.IntegerField(default=0)

    def __str__(self):
        return self.quick_note

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(deys=1)

class Comment(models.Model):
    text = models.CharField(max_length=200)
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date published')

blog/forms.py
from django import forms
from django.forms import ModelForm
from .models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={"placeholder": "Leave your comment or ask a question if you have!", "class": "comment-textarea textarea has-fixed-size", "id": "comment-textarea", "rows": 5})}

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.urls import reverse
from .models import Note, Comment
from .forms import CommentForm
from django.utils import timezone
from django.http import JsonResponse

# Create your views here.
def home(request):
    return render(request, 'blog/home.html')

def posts_list(request):
    posts_list = Note.objects.order_by('-pub_date')[:5]
    context = {'posts_list': posts_list}
    return render(request, 'blog/posts_list.html', context)

def note(request, id):
    note = get_object_or_404(Note, pk=id)
    comment = Comment.objects.filter(note_id=id).order_by('-id')
    form = CommentForm()
    return render(request, 'blog/note.html', {'note': note, 'comment': comment, 'form': form})

def comments(request):
    if request.is_ajax() and request.method == 'POST':
        comment = Comment(text=request.POST['comment'], note_id=request.POST['id'], pub_date=timezone.now())
        comment.save()
    return HttpResponse('fine')


def like(request):
    if request.is_ajax() and request.method == 'POST':
        print(request.POST['color'])
        note = get_object_or_404(Note, id=request.POST['id'])
        print(note.like)
        if request.POST['color'] == 'red':
            note.like += 1
        else:
            if note.like != 0:
                note.like -= 1
        print(note.like)
        Note.objects.filter(id=1).update(like=note.like)
        return HttpResponse(note.like)

blog/templates/blog/base.html
<!DOCTYPE html>
<html>
  <head>
    {% block head %}

      {% load static %}
      <link rel="stylesheet" type="text/css" href={% static 'blog/mystyles.css' %}>
      <link rel="stylesheet" type="text/css" href={% static 'blog/fontawesome/css/all.css' %}>
      <link rel="stylesheet" type="text/css" href={% static 'blog/fontawesome/css/fontawesome.css' %}>
      <link rel="stylesheet" type="text/css" href={% static 'blog/fontawesome/css/brands.css' %}>
      <link rel="stylesheet" type="text/css" href={% static 'blog/fontawesome/css/solid.css' %}>
      <script src={% static 'blog/jquery.min.js' %}></script>
      <meta name="viewport" content="width=device-width, ini:tial-scale=1">

    {% endblock head %}

  </head>
  <body style="background-color: #f29fd5;">
    {% block navbar %}

      <nav class="navbar is-transparent" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a href="/blog/" class="navbar-item underline">HOME</a>
          <a role="button" class="navbar-burger" id="burger" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div class="navbar-menu" id="nav-links">
          <div class="navbar-start">
            <a href="/blog/quicknotes/" class="navbar-item underline">QUICK NOTES</a>
            <a href="#" class="navbar-item underline">REFRENCES</a>
            <a href="#" class="navbar-item underline">MUSIC</a>
          </div>
        </div>
      </nav>

    {% endblock navbar %}

    <section class="container section">
        {% block content %}{% endblock content %}
        {% block comment %}{% endblock comment %}
    </section>

    {% block footer %}{% endblock footer %}

    <script>
      document.addEventListener('DOMContentLoaded', () => {
          (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
              const $notification = $delete.parentNode;

              $delete.addEventListener('click', () => {
                  $notification.parentNode.removeChild($notification);
              });
          });
      });


      $(document).ready(function() {
          $('.fa-heart').click(function(e){
              this.style.color = this.style.color == 'red' ? 'white' : 'red';
              e.preventDefault();

              $.ajax({
                  type:'POST',
                  url: "{% url 'blog:like' %}",
                  data:{
                      id: "{{ note.id }}",
                      color: document.getElementById("fa-heart").style.color,
                      csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                  },
                  success: function(resp){
                      $('#likes').text(resp);
                  },
                  error : function() {
                      console.log("Error");
                  }
              });
          });
      });


      const burgerIcon = document.querySelector('#burger');
      const navbarMenu = document.querySelector('#nav-links');

      burgerIcon.addEventListener('click', () => {
          navbarMenu.classList.toggle('is-active');
      });


      $(document).ready(function() {
          $('.button').click(function(e){
              e.preventDefault();

              $.ajax({
                  type:'POST',
                  url: "{% url 'blog:comments' %}",
                  data:{
                      id: "{{ note.id }}",
                      comment: document.getElementById("comment-textarea").value,
                      csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                  },
                  success: function(resp){
                      document.getElementById("good").style.display = "block";
                  },
                  error: function(resp) {
                      document.getElementById("bad").style.display = "block";
                  }
              });
          });
      });
    </script>

  </body>
</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% block content %}

  <section class="section">
    <p class="intro">Hello and Welcome to my little blog. My name is Niloofar and I'm a senior programmer.<br>
      I'm learning the beautiful Korean language, and I'm going to share my quick notes with everybody who wants to learn the same way. Hope it helps and you enjoy.<br>
      If you have any question about the notes, let me know. I'll help you if I know the answer.</p>

      <h2 class="korean-qoute qoute korean">세상에는 수백 개의 언어가 있지만, 미소는 그들 모두를 말합니다.</h2>
      <h2 class="english-qoute qoute">There are hundreds of languages in the world, but a smile speaks them all.</h2>


    <img class="hello-img" src="../../static/blog/img/hello.png" alt="Girl in a jacket">
    <img class="welcome-img" src="../../static/blog/img/welcome.png" alt="Girl in a jacket">

    <section class="section welcome">
      <img src="https://i.postimg.cc/9ff06qpd/korean-welcome-1.png" alt="Girl in a jacket">
    </section>

  </section>

{% endblock content %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}

  <section class="section">
    {% if latest_quick_notes %}
      {% for note in latest_quick_notes %}
        <div class="column is-full">
          <article id="post-list">
            <h2 class="title"><a href="{% url 'blog:note' note.id %}">{{ note.title }}</a></h2>
            <i class="subtitle">- Note {{ note.id }} - {{ note.pub_date }}</i>
          </article>
        </div>
      {% endfor %}
    {% else %}
      <p>No notes are available.</a>
    {% endif %}
  </section>

{% endblock content %}

blog/templates/blog/note.html
{% extends "blog/base.html" %}

{% block content %}

  <section class="section">
    <div class="column is-full">
      <article id="post">
        <h1 class="title is-2">{{ note.title }}</h1>
        <i class="subtitle">By: {{ note.author }} - {{ note.pub_date }}</i>
        <hr id="note-hr-top">
        <p>{{ note.quick_note }}</p>
        <hr id="note-hr-bottom">
        <i class="fas fa-heart" id="fa-heart"></i>
        <b id="likes">{{ note.like }}</b>
      </article>
  </div>


      <div class="notification" id="good" style="display:none">
        <button class="delete"></button>
        <p><strong> I'll receive your comment. Thank you! </strong></p>
      </div>

      <div class="notification" id="bad" style="display:none">
        <button class="delete"></button>
        <p><strong> Oops! We couldn't submit your comment. Please try again later. </strong></p>
      </div>

    <div class="column is-full">
      <div class="comment-form">
        <form action="{% url 'blog:comments'%}" method="post"">
          {% csrf_token %}
          <div class="field">
            <div class="control">
              {{ form }}
            </div>
          </div>
          <div class="field">
            <div class="control">
              <input type="submit" value="Send" class="button">
            </div>
          </div>
        </form>
      </div>
    </div>
  </section>

{% endblock content %}
{% block comment %}

  <section class="section">
    {% for each in comment %}
      <div class="column is-full">
        <div class="card">
          <header class="card-header">
            <p class="card-header-title">
              {{ each.id }}
            </p>
          </header>
          <div class="card-content">
            <p>
              {{ each.text }}
            </p>
          </div>
          <footer class="card-footer">
            <p class="card-footer-item">
              <span>
                {{ each.pub_date }}
              </span>
            </p>
            <p class="card-footer-item">
              <span></span>
            </p>
          </footer>
        </div>
      </div>
    {% endfor %}
  </section>

{% endblock comment %}

blog/templates/blog/posts_list.html
{% extends "blog/base.html" %}

{% block content %}

  <section class="section">
    {% if posts_list %}
      {% for note in posts_list %}
        <div class="column is-full">
          <article id="post-list">
            <h2 class="title"><a href="{% url 'blog:note' note.id %}">{{ note.title }}</a></h2>
            <i class="subtitle">- Note {{ note.id }} - {{ note.pub_date }}</i>
          </article>
        </div>
      {% endfor %}
    {% else %}
      <p>No notes are available.</a>
    {% endif %}
  </section>

{% endblock content %}